# Generated by Django 6.0.7 on 2026-07-23 11:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('request_path', models.CharField(max_length=255)),
                ('request_hash', models.CharField(max_length=64)),
                ('response_status', models.IntegerField()),
                ('response_body', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('aggregate_type', models.CharField(default='PaymentTransaction', max_length=50)),
                ('aggregate_id', models.CharField(max_length=100)),
                ('event_type', models.CharField(max_length=100)),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('retry_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationReport',
            fields=[
                ('report_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('total_records_checked', models.IntegerField(default=0)),
                ('matched_records', models.IntegerField(default=0)),
                ('discrepancy_count', models.IntegerField(default=0)),
                ('status', models.CharField(default='COMPLETED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('razorpay_customer_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=10000.0, max_digits=14)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MerchantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('business_name', models.CharField(max_length=255)),
                ('api_key', models.CharField(db_index=True, max_length=100, unique=True)),
                ('api_secret_hash', models.CharField(max_length=255)),
                ('webhook_secret', models.CharField(blank=True, default='', max_length=255)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('reserved_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('razorpay_order_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('AUTHORIZED', 'Authorized'), ('CAPTURED', 'Captured (Clearing)'), ('SETTLED', 'Settled'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], db_index=True, default='CREATED', max_length=20)),
                ('failure_reason', models.CharField(choices=[('NONE', 'None'), ('INSUFFICIENT_FUNDS', 'Insufficient Funds'), ('INVALID_CARD', 'Invalid Card Data'), ('FRAUD_RISK_BLOCK', 'Fraud Risk Blocked'), ('GATEWAY_UNAVAILABLE', 'Gateway Unavailable'), ('DUPLICATE_REQUEST_REJECTED', 'Duplicate Request Rejected'), ('INVALID_SIGNATURE', 'Invalid Webhook Signature')], default='NONE', max_length=50)),
                ('failure_message', models.TextField(blank=True, default='')),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_reconciled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='paymentGatewaySystem.customerprofile')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='paymentGatewaySystem.merchantprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiscrepancyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discrepancy_type', models.CharField(choices=[('MISSING_IN_LOCAL', 'Record Missing in Local DB'), ('MISSING_IN_GATEWAY', 'Record Missing in Razorpay Gateway'), ('STATUS_MISMATCH', 'Status Mismatch Between Systems'), ('AMOUNT_MISMATCH', 'Amount Mismatch Between Systems')], max_length=50)),
                ('details', models.JSONField()),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paymentGatewaySystem.paymenttransaction')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discrepancies', to='paymentGatewaySystem.reconciliationreport')),
            ],
        ),
        migrations.CreateModel(
            name='SagaStateLog',
            fields=[
                ('saga_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_step', models.CharField(max_length=50)),
                ('state', models.CharField(choices=[('STARTED', 'Started'), ('COMMITTED', 'Committed'), ('COMPENSATING', 'Compensating'), ('COMPENSATED', 'Compensated'), ('FAILED', 'Failed')], default='STARTED', max_length=20)),
                ('payload', models.JSONField(default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saga_logs', to='paymentGatewaySystem.paymenttransaction')),
            ],
        ),
        migrations.CreateModel(
            name='CardTokenVault',
            fields=[
                ('token_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('encrypted_payload', models.TextField(help_text='AES-256-GCM encrypted card vault token')),
                ('last4', models.CharField(max_length=4)),
                ('card_network', models.CharField(default='Visa', max_length=20)),
                ('expiry_month', models.IntegerField()),
                ('expiry_year', models.IntegerField()),
                ('fingerprint', models.CharField(db_index=True, max_length=64)),
                ('razorpay_token_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_tokens', to='paymentGatewaySystem.customerprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['customer', 'fingerprint'], name='paymentGate_custome_b40b77_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['status', 'created_at'], name='paymentGate_status_c476d8_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['merchant', 'status'], name='paymentGate_merchan_c2a740_idx'),
        ),
    ]
